/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTimetableRouteImport } from './routes/_authed/timetable'
import { Route as AuthedTimerRouteImport } from './routes/_authed/timer'
import { Route as AuthedNotesRouteImport } from './routes/_authed/notes'
import { Route as AuthedExamsRouteImport } from './routes/_authed/exams'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedAnalyticsRouteImport } from './routes/_authed/analytics'
import { Route as AuthedClassesIndexRouteImport } from './routes/_authed/classes/index'
import { Route as AuthedClassesClassIdRouteImport } from './routes/_authed/classes/$classId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTimetableRoute = AuthedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimerRoute = AuthedTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotesRoute = AuthedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExamsRoute = AuthedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsRoute = AuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClassesIndexRoute = AuthedClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClassesClassIdRoute = AuthedClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/exams': typeof AuthedExamsRoute
  '/notes': typeof AuthedNotesRoute
  '/timer': typeof AuthedTimerRoute
  '/timetable': typeof AuthedTimetableRoute
  '/classes/$classId': typeof AuthedClassesClassIdRoute
  '/classes/': typeof AuthedClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/exams': typeof AuthedExamsRoute
  '/notes': typeof AuthedNotesRoute
  '/timer': typeof AuthedTimerRoute
  '/timetable': typeof AuthedTimetableRoute
  '/classes/$classId': typeof AuthedClassesClassIdRoute
  '/classes': typeof AuthedClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/analytics': typeof AuthedAnalyticsRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/exams': typeof AuthedExamsRoute
  '/_authed/notes': typeof AuthedNotesRoute
  '/_authed/timer': typeof AuthedTimerRoute
  '/_authed/timetable': typeof AuthedTimetableRoute
  '/_authed/classes/$classId': typeof AuthedClassesClassIdRoute
  '/_authed/classes/': typeof AuthedClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/exams'
    | '/notes'
    | '/timer'
    | '/timetable'
    | '/classes/$classId'
    | '/classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/exams'
    | '/notes'
    | '/timer'
    | '/timetable'
    | '/classes/$classId'
    | '/classes'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/analytics'
    | '/_authed/calendar'
    | '/_authed/dashboard'
    | '/_authed/exams'
    | '/_authed/notes'
    | '/_authed/timer'
    | '/_authed/timetable'
    | '/_authed/classes/$classId'
    | '/_authed/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/timetable': {
      id: '/_authed/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthedTimetableRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timer': {
      id: '/_authed/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof AuthedTimerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notes': {
      id: '/_authed/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedNotesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exams': {
      id: '/_authed/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthedExamsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics': {
      id: '/_authed/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthedAnalyticsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/classes/': {
      id: '/_authed/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthedClassesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/classes/$classId': {
      id: '/_authed/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthedClassesClassIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAnalyticsRoute: typeof AuthedAnalyticsRoute
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedExamsRoute: typeof AuthedExamsRoute
  AuthedNotesRoute: typeof AuthedNotesRoute
  AuthedTimerRoute: typeof AuthedTimerRoute
  AuthedTimetableRoute: typeof AuthedTimetableRoute
  AuthedClassesClassIdRoute: typeof AuthedClassesClassIdRoute
  AuthedClassesIndexRoute: typeof AuthedClassesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAnalyticsRoute: AuthedAnalyticsRoute,
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedExamsRoute: AuthedExamsRoute,
  AuthedNotesRoute: AuthedNotesRoute,
  AuthedTimerRoute: AuthedTimerRoute,
  AuthedTimetableRoute: AuthedTimetableRoute,
  AuthedClassesClassIdRoute: AuthedClassesClassIdRoute,
  AuthedClassesIndexRoute: AuthedClassesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
